version: "3.7"

services: 

    redis:
        image: redis:latest
        ports:
            - 6379:6379

        volumes:
            - ./data:/data
            # - ./redis.conf:/usr/local/etc/redis/redis.conf
        
        # Add the custom redis.conf file if needed.    
        command: ["redis-server", "--appendonly", "yes", "requirepass", "change-this", "--maxmemory", "256mb", "--maxmemory-policy"]

        # redis-commander:
            
        #     image: rediscommander/redis-commander:latest

        #     ports:
        #         - 8081:8081
            
        #     environment:
        #       - REDIS_HOSTS=local:redis:6379
        #       - HTTP_USER=redis-user
        #       - HTTP_PASSWORD=change-this
            
        #     depends_on:
        #       - redis
            
        volumes:
          data:
